import { NeetChapter } from '../types';

export const ALL_81_NEET_CHAPTERS: NeetChapter[] = [
  // ==========================================
  // PHYSICS (20 Units)
  // ==========================================
  {
    id: 'phy-1',
    subject: 'Physics',
    title: 'Physics and Measurement',
    unitName: 'Unit 1: Physical World and Measurement',
    classLevel: 'Class 11',
    weightagePercentage: 4,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-10',
    revisionCount: 3,
    studyTimeMinutes: 240,
    questionsSolved: 65,
    questionsCorrect: 58,
    questionsWrong: 5,
    questionsUnattempted: 2,
    accuracyPercentage: 89,
    mockTestScore: 88,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false,
    notes: 'Dimensional analysis, errors in measurement, vernier calipers & screw gauge.'
  },
  {
    id: 'phy-2',
    subject: 'Physics',
    title: 'Kinematics',
    unitName: 'Unit 2: Kinematics',
    classLevel: 'Class 11',
    weightagePercentage: 8,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-12',
    revisionCount: 2,
    studyTimeMinutes: 380,
    questionsSolved: 110,
    questionsCorrect: 92,
    questionsWrong: 12,
    questionsUnattempted: 6,
    accuracyPercentage: 84,
    mockTestScore: 82,
    difficulty: 'Moderate',
    isBookmarked: true,
    priority: 'High',
    isWeakTopic: false,
    notes: 'Motion in a straight line, projectile motion equations, relative velocity vectors.'
  },
  {
    id: 'phy-3',
    subject: 'Physics',
    title: 'Laws of Motion',
    unitName: 'Unit 3: Laws of Motion',
    classLevel: 'Class 11',
    weightagePercentage: 7,
    status: 'In Progress',
    completionPercentage: 65,
    targetCompletionDate: '2026-09-22',
    revisionCount: 1,
    studyTimeMinutes: 280,
    questionsSolved: 75,
    questionsCorrect: 58,
    questionsWrong: 12,
    questionsUnattempted: 5,
    accuracyPercentage: 77,
    difficulty: 'Hard',
    isBookmarked: true,
    priority: 'High',
    isWeakTopic: false,
    notes: 'Free body diagrams, friction on inclined planes, banking of roads, pseudo forces.'
  },
  {
    id: 'phy-4',
    subject: 'Physics',
    title: 'Work, Energy and Power',
    unitName: 'Unit 4: Work, Energy and Power',
    classLevel: 'Class 11',
    weightagePercentage: 6,
    status: 'In Progress',
    completionPercentage: 50,
    targetCompletionDate: '2026-09-28',
    revisionCount: 1,
    studyTimeMinutes: 210,
    questionsSolved: 50,
    questionsCorrect: 40,
    questionsWrong: 7,
    questionsUnattempted: 3,
    accuracyPercentage: 80,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false,
    notes: 'Work-energy theorem, conservative forces, 1D & 2D elastic collisions, vertical circular motion.'
  },
  {
    id: 'phy-5',
    subject: 'Physics',
    title: 'Rotational Motion',
    unitName: 'Unit 5: Motion of System of Particles and Rigid Body',
    classLevel: 'Class 11',
    weightagePercentage: 8,
    status: 'Weak Area',
    completionPercentage: 35,
    targetCompletionDate: '2026-10-05',
    revisionCount: 0,
    studyTimeMinutes: 190,
    questionsSolved: 45,
    questionsCorrect: 26,
    questionsWrong: 15,
    questionsUnattempted: 4,
    accuracyPercentage: 58,
    difficulty: 'Very Hard',
    isBookmarked: true,
    priority: 'Urgent',
    isWeakTopic: true,
    notes: 'Moment of inertia theorems, rolling without slipping, angular momentum conservation.'
  },
  {
    id: 'phy-6',
    subject: 'Physics',
    title: 'Gravitation',
    unitName: 'Unit 6: Gravitation',
    classLevel: 'Class 11',
    weightagePercentage: 5,
    status: 'Revision',
    completionPercentage: 90,
    lastRevisionDate: '2026-09-08',
    revisionCount: 2,
    studyTimeMinutes: 180,
    questionsSolved: 60,
    questionsCorrect: 52,
    questionsWrong: 6,
    questionsUnattempted: 2,
    accuracyPercentage: 87,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false,
    notes: 'Keplers laws, gravitational potential energy, escape velocity, geostationary satellites.'
  },
  {
    id: 'phy-7',
    subject: 'Physics',
    title: 'Properties of Solids and Liquids',
    unitName: 'Unit 7: Properties of Bulk Matter',
    classLevel: 'Class 11',
    weightagePercentage: 6,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-10-18',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'phy-8',
    subject: 'Physics',
    title: 'Thermodynamics',
    unitName: 'Unit 8: Thermodynamics',
    classLevel: 'Class 11',
    weightagePercentage: 9,
    status: 'In Progress',
    completionPercentage: 45,
    targetCompletionDate: '2026-10-25',
    revisionCount: 1,
    studyTimeMinutes: 160,
    questionsSolved: 40,
    questionsCorrect: 31,
    questionsWrong: 7,
    questionsUnattempted: 2,
    accuracyPercentage: 78,
    difficulty: 'Moderate',
    isBookmarked: true,
    priority: 'High',
    isWeakTopic: false,
    notes: 'First law of thermodynamics, isothermal/adiabatic processes, Carnot engine efficiency.'
  },
  {
    id: 'phy-9',
    subject: 'Physics',
    title: 'Kinetic Theory of Gases',
    unitName: 'Unit 9: Behaviour of Perfect Gas and Kinetic Theory',
    classLevel: 'Class 11',
    weightagePercentage: 4,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-11-02',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  },
  {
    id: 'phy-10',
    subject: 'Physics',
    title: 'Oscillations and Waves',
    unitName: 'Unit 10: Oscillations and Waves',
    classLevel: 'Class 11',
    weightagePercentage: 7,
    status: 'In Progress',
    completionPercentage: 40,
    targetCompletionDate: '2026-11-12',
    revisionCount: 0,
    studyTimeMinutes: 120,
    questionsSolved: 35,
    questionsCorrect: 25,
    questionsWrong: 8,
    questionsUnattempted: 2,
    accuracyPercentage: 71,
    difficulty: 'Hard',
    isBookmarked: true,
    priority: 'High',
    isWeakTopic: false,
    notes: 'Simple harmonic motion equations, spring-mass systems, standing waves, Doppler effect.'
  },
  {
    id: 'phy-11',
    subject: 'Physics',
    title: 'Electrostatics',
    unitName: 'Unit 11: Electrostatics',
    classLevel: 'Class 12',
    weightagePercentage: 9,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-04',
    revisionCount: 3,
    studyTimeMinutes: 320,
    questionsSolved: 90,
    questionsCorrect: 80,
    questionsWrong: 7,
    questionsUnattempted: 3,
    accuracyPercentage: 89,
    mockTestScore: 88,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false,
    notes: 'Coulombs Law, Gauss Theorem applications, electric dipole, parallel plate capacitors with dielectrics.'
  },
  {
    id: 'phy-12',
    subject: 'Physics',
    title: 'Current Electricity',
    unitName: 'Unit 12: Current Electricity',
    classLevel: 'Class 12',
    weightagePercentage: 8,
    status: 'Revision',
    completionPercentage: 90,
    lastRevisionDate: '2026-09-14',
    revisionCount: 2,
    studyTimeMinutes: 290,
    questionsSolved: 85,
    questionsCorrect: 74,
    questionsWrong: 8,
    questionsUnattempted: 3,
    accuracyPercentage: 87,
    mockTestScore: 85,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false,
    notes: 'Drift velocity, Kirchhoffs Laws, Wheatstone bridge, potentiometer & meter bridge principles.'
  },
  {
    id: 'phy-13',
    subject: 'Physics',
    title: 'Magnetic Effects of Current and Magnetism',
    unitName: 'Unit 13: Magnetic Effects of Current and Magnetism',
    classLevel: 'Class 12',
    weightagePercentage: 8,
    status: 'In Progress',
    completionPercentage: 60,
    targetCompletionDate: '2026-10-10',
    revisionCount: 1,
    studyTimeMinutes: 180,
    questionsSolved: 50,
    questionsCorrect: 41,
    questionsWrong: 7,
    questionsUnattempted: 2,
    accuracyPercentage: 82,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'phy-14',
    subject: 'Physics',
    title: 'Electromagnetic Induction and Alternating Currents',
    unitName: 'Unit 14: Electromagnetic Induction and Alternating Currents',
    classLevel: 'Class 12',
    weightagePercentage: 8,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-11-20',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Hard',
    isBookmarked: true,
    priority: 'High',
    isWeakTopic: false
  },
  {
    id: 'phy-15',
    subject: 'Physics',
    title: 'Electromagnetic Waves',
    unitName: 'Unit 15: Electromagnetic Waves',
    classLevel: 'Class 12',
    weightagePercentage: 3,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-08-28',
    revisionCount: 2,
    studyTimeMinutes: 90,
    questionsSolved: 30,
    questionsCorrect: 28,
    questionsWrong: 2,
    questionsUnattempted: 0,
    accuracyPercentage: 93,
    mockTestScore: 92,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  },
  {
    id: 'phy-16',
    subject: 'Physics',
    title: 'Optics',
    unitName: 'Unit 16: Optics',
    classLevel: 'Class 12',
    weightagePercentage: 10,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-12-01',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Hard',
    isBookmarked: true,
    priority: 'Urgent',
    isWeakTopic: false
  },
  {
    id: 'phy-17',
    subject: 'Physics',
    title: 'Dual Nature of Matter and Radiation',
    unitName: 'Unit 17: Dual Nature of Matter and Radiation',
    classLevel: 'Class 12',
    weightagePercentage: 5,
    status: 'Revision',
    completionPercentage: 85,
    lastRevisionDate: '2026-09-02',
    revisionCount: 2,
    studyTimeMinutes: 140,
    questionsSolved: 45,
    questionsCorrect: 40,
    questionsWrong: 4,
    questionsUnattempted: 1,
    accuracyPercentage: 89,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'phy-18',
    subject: 'Physics',
    title: 'Atoms and Nuclei',
    unitName: 'Unit 18: Atoms and Nuclei',
    classLevel: 'Class 12',
    weightagePercentage: 6,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-12-15',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'phy-19',
    subject: 'Physics',
    title: 'Electronic Devices',
    unitName: 'Unit 19: Electronic Devices',
    classLevel: 'Class 12',
    weightagePercentage: 7,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-12-28',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false
  },
  {
    id: 'phy-20',
    subject: 'Physics',
    title: 'Experimental Skills',
    unitName: 'Unit 20: Experimental Skills',
    classLevel: 'Class 11',
    weightagePercentage: 3,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2027-01-10',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  },

  // ==========================================
  // CHEMISTRY (20 Units)
  // ==========================================
  {
    id: 'chem-1',
    subject: 'Chemistry',
    title: 'Some Basic Concepts of Chemistry',
    unitName: 'Physical Chemistry',
    classLevel: 'Class 11',
    weightagePercentage: 5,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-11',
    revisionCount: 3,
    studyTimeMinutes: 200,
    questionsSolved: 70,
    questionsCorrect: 64,
    questionsWrong: 4,
    questionsUnattempted: 2,
    accuracyPercentage: 91,
    mockTestScore: 92,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false,
    notes: 'Mole concept, limiting reagent, molarity, molality, normality numericals.'
  },
  {
    id: 'chem-2',
    subject: 'Chemistry',
    title: 'Atomic Structure',
    unitName: 'Physical Chemistry',
    classLevel: 'Class 11',
    weightagePercentage: 6,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-13',
    revisionCount: 3,
    studyTimeMinutes: 260,
    questionsSolved: 80,
    questionsCorrect: 73,
    questionsWrong: 5,
    questionsUnattempted: 2,
    accuracyPercentage: 91,
    mockTestScore: 90,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false,
    notes: 'Bohrs model, de Broglie wavelength, Heisenberg uncertainty, quantum numbers, electronic configuration.'
  },
  {
    id: 'chem-3',
    subject: 'Chemistry',
    title: 'Chemical Bonding and Molecular Structure',
    unitName: 'Inorganic Chemistry',
    classLevel: 'Class 11',
    weightagePercentage: 9,
    status: 'Revision',
    completionPercentage: 95,
    lastRevisionDate: '2026-09-14',
    revisionCount: 3,
    studyTimeMinutes: 340,
    questionsSolved: 120,
    questionsCorrect: 106,
    questionsWrong: 11,
    questionsUnattempted: 3,
    accuracyPercentage: 88,
    mockTestScore: 89,
    difficulty: 'Hard',
    isBookmarked: true,
    priority: 'Urgent',
    isWeakTopic: false,
    notes: 'VSEPR theory shapes, hybridization, molecular orbital theory (MOT), hydrogen bonding.'
  },
  {
    id: 'chem-4',
    subject: 'Chemistry',
    title: 'Chemical Thermodynamics',
    unitName: 'Physical Chemistry',
    classLevel: 'Class 11',
    weightagePercentage: 8,
    status: 'In Progress',
    completionPercentage: 60,
    targetCompletionDate: '2026-09-26',
    revisionCount: 1,
    studyTimeMinutes: 220,
    questionsSolved: 55,
    questionsCorrect: 42,
    questionsWrong: 10,
    questionsUnattempted: 3,
    accuracyPercentage: 76,
    difficulty: 'Hard',
    isBookmarked: true,
    priority: 'High',
    isWeakTopic: false,
    notes: 'State functions, Hesss law, entropy and Gibbs free energy criteria for spontaneity.'
  },
  {
    id: 'chem-5',
    subject: 'Chemistry',
    title: 'Solutions',
    unitName: 'Physical Chemistry',
    classLevel: 'Class 12',
    weightagePercentage: 7,
    status: 'In Progress',
    completionPercentage: 40,
    targetCompletionDate: '2026-10-08',
    revisionCount: 1,
    studyTimeMinutes: 150,
    questionsSolved: 40,
    questionsCorrect: 32,
    questionsWrong: 6,
    questionsUnattempted: 2,
    accuracyPercentage: 80,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'chem-6',
    subject: 'Chemistry',
    title: 'Equilibrium',
    unitName: 'Physical Chemistry',
    classLevel: 'Class 11',
    weightagePercentage: 8,
    status: 'Weak Area',
    completionPercentage: 35,
    targetCompletionDate: '2026-10-15',
    revisionCount: 0,
    studyTimeMinutes: 170,
    questionsSolved: 45,
    questionsCorrect: 27,
    questionsWrong: 14,
    questionsUnattempted: 4,
    accuracyPercentage: 60,
    difficulty: 'Very Hard',
    isBookmarked: true,
    priority: 'Urgent',
    isWeakTopic: true,
    notes: 'Le Chatelier principle, pH of buffer solutions, common ion effect, solubility product (Ksp).'
  },
  {
    id: 'chem-7',
    subject: 'Chemistry',
    title: 'Redox Reactions and Electrochemistry',
    unitName: 'Physical Chemistry',
    classLevel: 'Class 12',
    weightagePercentage: 8,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-10-28',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false
  },
  {
    id: 'chem-8',
    subject: 'Chemistry',
    title: 'Chemical Kinetics',
    unitName: 'Physical Chemistry',
    classLevel: 'Class 12',
    weightagePercentage: 7,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-11-05',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'chem-9',
    subject: 'Chemistry',
    title: 'Classification of Elements and Periodicity in Properties',
    unitName: 'Inorganic Chemistry',
    classLevel: 'Class 11',
    weightagePercentage: 5,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-08-30',
    revisionCount: 3,
    studyTimeMinutes: 160,
    questionsSolved: 50,
    questionsCorrect: 47,
    questionsWrong: 2,
    questionsUnattempted: 1,
    accuracyPercentage: 94,
    mockTestScore: 95,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  },
  {
    id: 'chem-10',
    subject: 'Chemistry',
    title: 'p-Block Elements',
    unitName: 'Inorganic Chemistry',
    classLevel: 'Class 11 & 12',
    weightagePercentage: 9,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-11-18',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Hard',
    isBookmarked: true,
    priority: 'Urgent',
    isWeakTopic: false
  },
  {
    id: 'chem-11',
    subject: 'Chemistry',
    title: 'd- and f-Block Elements',
    unitName: 'Inorganic Chemistry',
    classLevel: 'Class 12',
    weightagePercentage: 7,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-11-28',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false
  },
  {
    id: 'chem-12',
    subject: 'Chemistry',
    title: 'Coordination Compounds',
    unitName: 'Inorganic Chemistry',
    classLevel: 'Class 12',
    weightagePercentage: 9,
    status: 'Revision',
    completionPercentage: 90,
    lastRevisionDate: '2026-09-05',
    revisionCount: 2,
    studyTimeMinutes: 240,
    questionsSolved: 75,
    questionsCorrect: 66,
    questionsWrong: 7,
    questionsUnattempted: 2,
    accuracyPercentage: 88,
    mockTestScore: 86,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false,
    notes: 'IUPAC nomenclature, Werner theory, crystal field theory (CFT) splitting, isomerism.'
  },
  {
    id: 'chem-13',
    subject: 'Chemistry',
    title: 'Purification and Characterisation of Organic Compounds',
    unitName: 'Organic Chemistry',
    classLevel: 'Class 11',
    weightagePercentage: 4,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-12-05',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  },
  {
    id: 'chem-14',
    subject: 'Chemistry',
    title: 'Some Basic Principles of Organic Chemistry',
    unitName: 'Organic Chemistry (GOC)',
    classLevel: 'Class 11',
    weightagePercentage: 10,
    status: 'Revision',
    completionPercentage: 95,
    lastRevisionDate: '2026-09-06',
    revisionCount: 3,
    studyTimeMinutes: 350,
    questionsSolved: 130,
    questionsCorrect: 114,
    questionsWrong: 12,
    questionsUnattempted: 4,
    accuracyPercentage: 88,
    mockTestScore: 88,
    difficulty: 'Hard',
    isBookmarked: true,
    priority: 'Urgent',
    isWeakTopic: false,
    notes: 'Inductive effect, resonance structures, hyperconjugation, aromaticity (Huckel rule), carbocation stability.'
  },
  {
    id: 'chem-15',
    subject: 'Chemistry',
    title: 'Hydrocarbons',
    unitName: 'Organic Chemistry',
    classLevel: 'Class 11',
    weightagePercentage: 8,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-08',
    revisionCount: 2,
    studyTimeMinutes: 280,
    questionsSolved: 90,
    questionsCorrect: 81,
    questionsWrong: 7,
    questionsUnattempted: 2,
    accuracyPercentage: 90,
    mockTestScore: 90,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false
  },
  {
    id: 'chem-16',
    subject: 'Chemistry',
    title: 'Organic Compounds Containing Halogens',
    unitName: 'Organic Chemistry (Haloalkanes)',
    classLevel: 'Class 12',
    weightagePercentage: 6,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-12-18',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'chem-17',
    subject: 'Chemistry',
    title: 'Organic Compounds Containing Oxygen',
    unitName: 'Organic Chemistry (Alcohols, Carbonyls)',
    classLevel: 'Class 12',
    weightagePercentage: 11,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2027-01-05',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Hard',
    isBookmarked: true,
    priority: 'Urgent',
    isWeakTopic: false
  },
  {
    id: 'chem-18',
    subject: 'Chemistry',
    title: 'Organic Compounds Containing Nitrogen',
    unitName: 'Organic Chemistry (Amines)',
    classLevel: 'Class 12',
    weightagePercentage: 7,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2027-01-18',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false
  },
  {
    id: 'chem-19',
    subject: 'Chemistry',
    title: 'Biomolecules',
    unitName: 'Organic Chemistry',
    classLevel: 'Class 12',
    weightagePercentage: 6,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-01',
    revisionCount: 3,
    studyTimeMinutes: 180,
    questionsSolved: 60,
    questionsCorrect: 56,
    questionsWrong: 3,
    questionsUnattempted: 1,
    accuracyPercentage: 93,
    mockTestScore: 94,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'chem-20',
    subject: 'Chemistry',
    title: 'Principles Related to Practical Chemistry',
    unitName: 'Practical Chemistry',
    classLevel: 'Class 11 & 12',
    weightagePercentage: 4,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2027-02-01',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  },

  // ==========================================
  // BOTANY (24 Chapters)
  // ==========================================
  {
    id: 'bot-1',
    subject: 'Botany',
    title: 'The Living World',
    unitName: 'Diversity in the Living World',
    classLevel: 'Class 11',
    weightagePercentage: 4,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-09',
    revisionCount: 4,
    studyTimeMinutes: 120,
    questionsSolved: 50,
    questionsCorrect: 48,
    questionsWrong: 2,
    questionsUnattempted: 0,
    accuracyPercentage: 96,
    mockTestScore: 96,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  },
  {
    id: 'bot-2',
    subject: 'Botany',
    title: 'Biological Classification',
    unitName: 'Diversity in the Living World',
    classLevel: 'Class 11',
    weightagePercentage: 7,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-12',
    revisionCount: 3,
    studyTimeMinutes: 240,
    questionsSolved: 80,
    questionsCorrect: 74,
    questionsWrong: 5,
    questionsUnattempted: 1,
    accuracyPercentage: 92,
    mockTestScore: 91,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'bot-3',
    subject: 'Botany',
    title: 'Plant Kingdom',
    unitName: 'Diversity in the Living World',
    classLevel: 'Class 11',
    weightagePercentage: 8,
    status: 'Revision',
    completionPercentage: 90,
    lastRevisionDate: '2026-09-03',
    revisionCount: 3,
    studyTimeMinutes: 280,
    questionsSolved: 85,
    questionsCorrect: 76,
    questionsWrong: 7,
    questionsUnattempted: 2,
    accuracyPercentage: 89,
    mockTestScore: 88,
    difficulty: 'Hard',
    isBookmarked: true,
    priority: 'High',
    isWeakTopic: false,
    notes: 'Algae classification pigments, bryophytes & pteridophytes life cycles, gymnosperm examples.'
  },
  {
    id: 'bot-4',
    subject: 'Botany',
    title: 'Morphology of Flowering Plants',
    unitName: 'Structural Organisation in Plants',
    classLevel: 'Class 11',
    weightagePercentage: 7,
    status: 'In Progress',
    completionPercentage: 55,
    targetCompletionDate: '2026-09-24',
    revisionCount: 1,
    studyTimeMinutes: 190,
    questionsSolved: 60,
    questionsCorrect: 48,
    questionsWrong: 9,
    questionsUnattempted: 3,
    accuracyPercentage: 80,
    difficulty: 'Hard',
    isBookmarked: true,
    priority: 'High',
    isWeakTopic: false,
    notes: 'Root/stem modifications, aestivation, placentation, floral formula of Solanaceae & Fabaceae.'
  },
  {
    id: 'bot-5',
    subject: 'Botany',
    title: 'Anatomy of Flowering Plants',
    unitName: 'Structural Organisation in Plants',
    classLevel: 'Class 11',
    weightagePercentage: 6,
    status: 'In Progress',
    completionPercentage: 40,
    targetCompletionDate: '2026-10-02',
    revisionCount: 1,
    studyTimeMinutes: 140,
    questionsSolved: 45,
    questionsCorrect: 35,
    questionsWrong: 8,
    questionsUnattempted: 2,
    accuracyPercentage: 78,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'bot-6',
    subject: 'Botany',
    title: 'Cell: The Unit of Life',
    unitName: 'Cell Structure and Function',
    classLevel: 'Class 11',
    weightagePercentage: 9,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-14',
    revisionCount: 4,
    studyTimeMinutes: 300,
    questionsSolved: 100,
    questionsCorrect: 94,
    questionsWrong: 4,
    questionsUnattempted: 2,
    accuracyPercentage: 94,
    mockTestScore: 94,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false,
    notes: 'Prokaryotic vs eukaryotic cell, endomembrane system, mitochondria & chloroplast structures, ribosome 70S/80S.'
  },
  {
    id: 'bot-7',
    subject: 'Botany',
    title: 'Biomolecules',
    unitName: 'Cell Structure and Function',
    classLevel: 'Class 11',
    weightagePercentage: 6,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-02',
    revisionCount: 3,
    studyTimeMinutes: 180,
    questionsSolved: 60,
    questionsCorrect: 55,
    questionsWrong: 4,
    questionsUnattempted: 1,
    accuracyPercentage: 92,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'bot-8',
    subject: 'Botany',
    title: 'Cell Cycle and Cell Division',
    unitName: 'Cell Structure and Function',
    classLevel: 'Class 11',
    weightagePercentage: 8,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-08',
    revisionCount: 3,
    studyTimeMinutes: 220,
    questionsSolved: 75,
    questionsCorrect: 70,
    questionsWrong: 4,
    questionsUnattempted: 1,
    accuracyPercentage: 93,
    mockTestScore: 92,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false,
    notes: 'Stages of Prophase 1 (Leptotene to Diakinesis), crossing over in Pachytene, spindle checkpoint.'
  },
  {
    id: 'bot-9',
    subject: 'Botany',
    title: 'Transport in Plants',
    unitName: 'Plant Physiology',
    classLevel: 'Class 11',
    weightagePercentage: 5,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-10-12',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'bot-10',
    subject: 'Botany',
    title: 'Mineral Nutrition',
    unitName: 'Plant Physiology',
    classLevel: 'Class 11',
    weightagePercentage: 4,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-10-20',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  },
  {
    id: 'bot-11',
    subject: 'Botany',
    title: 'Photosynthesis in Higher Plants',
    unitName: 'Plant Physiology',
    classLevel: 'Class 11',
    weightagePercentage: 9,
    status: 'In Progress',
    completionPercentage: 60,
    targetCompletionDate: '2026-10-30',
    revisionCount: 1,
    studyTimeMinutes: 240,
    questionsSolved: 70,
    questionsCorrect: 58,
    questionsWrong: 9,
    questionsUnattempted: 3,
    accuracyPercentage: 83,
    difficulty: 'Hard',
    isBookmarked: true,
    priority: 'Urgent',
    isWeakTopic: false,
    notes: 'Z-scheme electron transport, Calvin cycle (C3), C4 pathway anatomy, photorespiration.'
  },
  {
    id: 'bot-12',
    subject: 'Botany',
    title: 'Respiration in Plants',
    unitName: 'Plant Physiology',
    classLevel: 'Class 11',
    weightagePercentage: 7,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-11-10',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false
  },
  {
    id: 'bot-13',
    subject: 'Botany',
    title: 'Plant Growth and Development',
    unitName: 'Plant Physiology',
    classLevel: 'Class 11',
    weightagePercentage: 5,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-11-20',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'bot-14',
    subject: 'Botany',
    title: 'Sexual Reproduction in Flowering Plants',
    unitName: 'Reproduction',
    classLevel: 'Class 12',
    weightagePercentage: 9,
    status: 'Revision',
    completionPercentage: 90,
    lastRevisionDate: '2026-09-04',
    revisionCount: 2,
    studyTimeMinutes: 270,
    questionsSolved: 85,
    questionsCorrect: 77,
    questionsWrong: 6,
    questionsUnattempted: 2,
    accuracyPercentage: 90,
    mockTestScore: 90,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false,
    notes: 'Microsporogenesis, megasporogenesis, double fertilization (syngamy + triple fusion), apomixis & polyembryony.'
  },
  {
    id: 'bot-15',
    subject: 'Botany',
    title: 'Principles of Inheritance and Variation',
    unitName: 'Genetics and Evolution',
    classLevel: 'Class 12',
    weightagePercentage: 12,
    status: 'In Progress',
    completionPercentage: 70,
    targetCompletionDate: '2026-09-30',
    revisionCount: 2,
    studyTimeMinutes: 380,
    questionsSolved: 140,
    questionsCorrect: 120,
    questionsWrong: 15,
    questionsUnattempted: 5,
    accuracyPercentage: 86,
    mockTestScore: 86,
    difficulty: 'Very Hard',
    isBookmarked: true,
    priority: 'Urgent',
    isWeakTopic: false,
    notes: 'Mendelian ratios, incomplete dominance, codominance, linkage and recombination (Morgan), pedigree charts.'
  },
  {
    id: 'bot-16',
    subject: 'Botany',
    title: 'Molecular Basis of Inheritance',
    unitName: 'Genetics and Evolution',
    classLevel: 'Class 12',
    weightagePercentage: 13,
    status: 'In Progress',
    completionPercentage: 65,
    targetCompletionDate: '2026-10-06',
    revisionCount: 2,
    studyTimeMinutes: 400,
    questionsSolved: 150,
    questionsCorrect: 128,
    questionsWrong: 16,
    questionsUnattempted: 6,
    accuracyPercentage: 85,
    difficulty: 'Very Hard',
    isBookmarked: true,
    priority: 'Urgent',
    isWeakTopic: false,
    notes: 'DNA replication semiconservative proof, transcription, genetic code properties, Lac operon regulation, DNA fingerprinting.'
  },
  {
    id: 'bot-17',
    subject: 'Botany',
    title: 'Strategies for Enhancement in Food Production',
    unitName: 'Biology in Human Welfare',
    classLevel: 'Class 12',
    weightagePercentage: 3,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-08-25',
    revisionCount: 2,
    studyTimeMinutes: 100,
    questionsSolved: 35,
    questionsCorrect: 33,
    questionsWrong: 2,
    questionsUnattempted: 0,
    accuracyPercentage: 94,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  },
  {
    id: 'bot-18',
    subject: 'Botany',
    title: 'Microbes in Human Welfare',
    unitName: 'Biology in Human Welfare',
    classLevel: 'Class 12',
    weightagePercentage: 5,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-07',
    revisionCount: 3,
    studyTimeMinutes: 150,
    questionsSolved: 50,
    questionsCorrect: 47,
    questionsWrong: 2,
    questionsUnattempted: 1,
    accuracyPercentage: 94,
    mockTestScore: 95,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'bot-19',
    subject: 'Botany',
    title: 'Organisms and Populations',
    unitName: 'Ecology and Environment',
    classLevel: 'Class 12',
    weightagePercentage: 6,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-11-28',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false
  },
  {
    id: 'bot-20',
    subject: 'Botany',
    title: 'Ecosystem',
    unitName: 'Ecology and Environment',
    classLevel: 'Class 12',
    weightagePercentage: 6,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-12-08',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'bot-21',
    subject: 'Botany',
    title: 'Biodiversity and Conservation',
    unitName: 'Ecology and Environment',
    classLevel: 'Class 12',
    weightagePercentage: 6,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-12-18',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'bot-22',
    subject: 'Botany',
    title: 'Environmental Issues',
    unitName: 'Ecology and Environment',
    classLevel: 'Class 12',
    weightagePercentage: 4,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-12-25',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  },
  {
    id: 'bot-23',
    subject: 'Botany',
    title: 'Biotechnology: Principles and Processes',
    unitName: 'Biotechnology',
    classLevel: 'Class 12',
    weightagePercentage: 8,
    status: 'In Progress',
    completionPercentage: 50,
    targetCompletionDate: '2027-01-08',
    revisionCount: 1,
    studyTimeMinutes: 180,
    questionsSolved: 55,
    questionsCorrect: 47,
    questionsWrong: 6,
    questionsUnattempted: 2,
    accuracyPercentage: 85,
    difficulty: 'Moderate',
    isBookmarked: true,
    priority: 'High',
    isWeakTopic: false
  },
  {
    id: 'bot-24',
    subject: 'Botany',
    title: 'Biotechnology and Its Applications',
    unitName: 'Biotechnology',
    classLevel: 'Class 12',
    weightagePercentage: 6,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2027-01-18',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false
  },

  // ==========================================
  // ZOOLOGY (27 Chapters)
  // ==========================================
  {
    id: 'zoo-1',
    subject: 'Zoology',
    title: 'Animal Kingdom',
    unitName: 'Diversity in the Living World',
    classLevel: 'Class 11',
    weightagePercentage: 9,
    status: 'Revision',
    completionPercentage: 90,
    lastRevisionDate: '2026-09-01',
    revisionCount: 3,
    studyTimeMinutes: 320,
    questionsSolved: 110,
    questionsCorrect: 96,
    questionsWrong: 11,
    questionsUnattempted: 3,
    accuracyPercentage: 87,
    mockTestScore: 88,
    difficulty: 'Hard',
    isBookmarked: true,
    priority: 'Urgent',
    isWeakTopic: false,
    notes: 'Non-chordates phyla characteristics, chordates classes, coelom types, symmetry.'
  },
  {
    id: 'zoo-2',
    subject: 'Zoology',
    title: 'Structural Organisation in Animals',
    unitName: 'Structural Organisation',
    classLevel: 'Class 11',
    weightagePercentage: 6,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-05',
    revisionCount: 2,
    studyTimeMinutes: 180,
    questionsSolved: 60,
    questionsCorrect: 53,
    questionsWrong: 5,
    questionsUnattempted: 2,
    accuracyPercentage: 88,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false,
    notes: 'Epithelial, connective, muscular, nervous tissues; Cockroach morphology & anatomy.'
  },
  {
    id: 'zoo-3',
    subject: 'Zoology',
    title: 'Human Physiology',
    unitName: 'Human Physiology Overview',
    classLevel: 'Class 11',
    weightagePercentage: 5,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-10',
    revisionCount: 3,
    studyTimeMinutes: 140,
    questionsSolved: 45,
    questionsCorrect: 42,
    questionsWrong: 2,
    questionsUnattempted: 1,
    accuracyPercentage: 93,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  },
  {
    id: 'zoo-4',
    subject: 'Zoology',
    title: 'Digestion and Absorption',
    unitName: 'Human Physiology',
    classLevel: 'Class 11',
    weightagePercentage: 5,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-08',
    revisionCount: 3,
    studyTimeMinutes: 180,
    questionsSolved: 65,
    questionsCorrect: 60,
    questionsWrong: 4,
    questionsUnattempted: 1,
    accuracyPercentage: 92,
    mockTestScore: 94,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'zoo-5',
    subject: 'Zoology',
    title: 'Breathing and Exchange of Gases',
    unitName: 'Human Physiology',
    classLevel: 'Class 11',
    weightagePercentage: 6,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-11',
    revisionCount: 2,
    studyTimeMinutes: 190,
    questionsSolved: 60,
    questionsCorrect: 55,
    questionsWrong: 4,
    questionsUnattempted: 1,
    accuracyPercentage: 92,
    mockTestScore: 90,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false,
    notes: 'Respiratory volumes & capacities (TV, IRV, ERV, RV, VC), oxygen-hemoglobin dissociation curve.'
  },
  {
    id: 'zoo-6',
    subject: 'Zoology',
    title: 'Body Fluids and Circulation',
    unitName: 'Human Physiology',
    classLevel: 'Class 11',
    weightagePercentage: 8,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-15',
    revisionCount: 3,
    studyTimeMinutes: 260,
    questionsSolved: 80,
    questionsCorrect: 74,
    questionsWrong: 4,
    questionsUnattempted: 2,
    accuracyPercentage: 93,
    mockTestScore: 92,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false,
    notes: 'Blood groups ABO & Rh, cardiac cycle events, ECG wave significance (P, QRS, T), double circulation.'
  },
  {
    id: 'zoo-7',
    subject: 'Zoology',
    title: 'Excretory Products and Their Elimination',
    unitName: 'Human Physiology',
    classLevel: 'Class 11',
    weightagePercentage: 7,
    status: 'In Progress',
    completionPercentage: 75,
    targetCompletionDate: '2026-09-25',
    revisionCount: 1,
    studyTimeMinutes: 200,
    questionsSolved: 60,
    questionsCorrect: 51,
    questionsWrong: 7,
    questionsUnattempted: 2,
    accuracyPercentage: 85,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false,
    notes: 'Nephron structure, counter-current mechanism in Henle loop, RAAS pathway, micturition reflex.'
  },
  {
    id: 'zoo-8',
    subject: 'Zoology',
    title: 'Locomotion and Movement',
    unitName: 'Human Physiology',
    classLevel: 'Class 11',
    weightagePercentage: 6,
    status: 'In Progress',
    completionPercentage: 50,
    targetCompletionDate: '2026-10-04',
    revisionCount: 1,
    studyTimeMinutes: 150,
    questionsSolved: 45,
    questionsCorrect: 36,
    questionsWrong: 7,
    questionsUnattempted: 2,
    accuracyPercentage: 80,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'zoo-9',
    subject: 'Zoology',
    title: 'Neural Control and Coordination',
    unitName: 'Human Physiology',
    classLevel: 'Class 11',
    weightagePercentage: 7,
    status: 'Weak Area',
    completionPercentage: 40,
    targetCompletionDate: '2026-10-14',
    revisionCount: 0,
    studyTimeMinutes: 160,
    questionsSolved: 50,
    questionsCorrect: 31,
    questionsWrong: 15,
    questionsUnattempted: 4,
    accuracyPercentage: 62,
    difficulty: 'Hard',
    isBookmarked: true,
    priority: 'Urgent',
    isWeakTopic: true,
    notes: 'Nerve impulse generation (action potential, Na/K pump), synaptic transmission, eye & ear structures.'
  },
  {
    id: 'zoo-10',
    subject: 'Zoology',
    title: 'Chemical Coordination and Integration',
    unitName: 'Human Physiology',
    classLevel: 'Class 11',
    weightagePercentage: 7,
    status: 'In Progress',
    completionPercentage: 65,
    targetCompletionDate: '2026-10-22',
    revisionCount: 1,
    studyTimeMinutes: 190,
    questionsSolved: 55,
    questionsCorrect: 46,
    questionsWrong: 7,
    questionsUnattempted: 2,
    accuracyPercentage: 84,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false
  },
  {
    id: 'zoo-11',
    subject: 'Zoology',
    title: 'Human Reproduction',
    unitName: 'Reproduction',
    classLevel: 'Class 12',
    weightagePercentage: 9,
    status: 'Revision',
    completionPercentage: 90,
    lastRevisionDate: '2026-09-07',
    revisionCount: 2,
    studyTimeMinutes: 290,
    questionsSolved: 90,
    questionsCorrect: 81,
    questionsWrong: 6,
    questionsUnattempted: 3,
    accuracyPercentage: 90,
    mockTestScore: 91,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false,
    notes: 'Spermatogenesis, oogenesis, menstrual cycle hormone spikes (LH/FSH), embryonic development & placenta.'
  },
  {
    id: 'zoo-12',
    subject: 'Zoology',
    title: 'Reproductive Health',
    unitName: 'Reproduction',
    classLevel: 'Class 12',
    weightagePercentage: 5,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-04',
    revisionCount: 3,
    studyTimeMinutes: 130,
    questionsSolved: 45,
    questionsCorrect: 43,
    questionsWrong: 1,
    questionsUnattempted: 1,
    accuracyPercentage: 96,
    mockTestScore: 96,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  },
  {
    id: 'zoo-13',
    subject: 'Zoology',
    title: 'Evolution',
    unitName: 'Genetics and Evolution',
    classLevel: 'Class 12',
    weightagePercentage: 8,
    status: 'In Progress',
    completionPercentage: 50,
    targetCompletionDate: '2026-11-04',
    revisionCount: 1,
    studyTimeMinutes: 180,
    questionsSolved: 60,
    questionsCorrect: 49,
    questionsWrong: 8,
    questionsUnattempted: 3,
    accuracyPercentage: 82,
    difficulty: 'Moderate',
    isBookmarked: true,
    priority: 'High',
    isWeakTopic: false,
    notes: 'Homologous vs analogous organs, Hardy-Weinberg equilibrium formula (p^2+2pq+q^2=1), human evolution ancestors.'
  },
  {
    id: 'zoo-14',
    subject: 'Zoology',
    title: 'Human Health and Disease',
    unitName: 'Biology and Human Welfare',
    classLevel: 'Class 12',
    weightagePercentage: 9,
    status: 'Revision',
    completionPercentage: 90,
    lastRevisionDate: '2026-09-06',
    revisionCount: 2,
    studyTimeMinutes: 260,
    questionsSolved: 80,
    questionsCorrect: 72,
    questionsWrong: 6,
    questionsUnattempted: 2,
    accuracyPercentage: 90,
    mockTestScore: 89,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false,
    notes: 'Pathogens & life cycle of Plasmodium (Malaria), innate vs acquired immunity, antibodies structure, AIDS & Cancer mechanisms.'
  },
  {
    id: 'zoo-15',
    subject: 'Zoology',
    title: 'Biotechnology: Principles and Processes',
    unitName: 'Biotechnology',
    classLevel: 'Class 12',
    weightagePercentage: 8,
    status: 'In Progress',
    completionPercentage: 60,
    targetCompletionDate: '2026-11-15',
    revisionCount: 1,
    studyTimeMinutes: 200,
    questionsSolved: 65,
    questionsCorrect: 55,
    questionsWrong: 7,
    questionsUnattempted: 3,
    accuracyPercentage: 85,
    difficulty: 'Hard',
    isBookmarked: true,
    priority: 'Urgent',
    isWeakTopic: false
  },
  {
    id: 'zoo-16',
    subject: 'Zoology',
    title: 'Biotechnology and Its Applications',
    unitName: 'Biotechnology',
    classLevel: 'Class 12',
    weightagePercentage: 7,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-11-25',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Moderate',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false
  },
  {
    id: 'zoo-17',
    subject: 'Zoology',
    title: 'Human Health, Immunity and Common Diseases',
    unitName: 'Biology in Human Welfare',
    classLevel: 'Class 12',
    weightagePercentage: 5,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-08-20',
    revisionCount: 2,
    studyTimeMinutes: 140,
    questionsSolved: 40,
    questionsCorrect: 38,
    questionsWrong: 2,
    questionsUnattempted: 0,
    accuracyPercentage: 95,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  },
  {
    id: 'zoo-18',
    subject: 'Zoology',
    title: 'Animal Husbandry',
    unitName: 'Biology in Human Welfare',
    classLevel: 'Class 12',
    weightagePercentage: 3,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-08-22',
    revisionCount: 2,
    studyTimeMinutes: 90,
    questionsSolved: 30,
    questionsCorrect: 28,
    questionsWrong: 2,
    questionsUnattempted: 0,
    accuracyPercentage: 93,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  },
  {
    id: 'zoo-19',
    subject: 'Zoology',
    title: 'Biology and Human Welfare',
    unitName: 'Biology and Human Welfare',
    classLevel: 'Class 12',
    weightagePercentage: 4,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2026-12-05',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  },
  {
    id: 'zoo-20',
    subject: 'Zoology',
    title: 'Principles of Inheritance and Variation',
    unitName: 'Genetics',
    classLevel: 'Class 12',
    weightagePercentage: 6,
    status: 'In Progress',
    completionPercentage: 65,
    targetCompletionDate: '2026-12-15',
    revisionCount: 1,
    studyTimeMinutes: 180,
    questionsSolved: 50,
    questionsCorrect: 42,
    questionsWrong: 6,
    questionsUnattempted: 2,
    accuracyPercentage: 84,
    difficulty: 'Hard',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false
  },
  {
    id: 'zoo-21',
    subject: 'Zoology',
    title: 'Molecular Basis of Inheritance',
    unitName: 'Genetics',
    classLevel: 'Class 12',
    weightagePercentage: 7,
    status: 'In Progress',
    completionPercentage: 60,
    targetCompletionDate: '2026-12-22',
    revisionCount: 1,
    studyTimeMinutes: 190,
    questionsSolved: 55,
    questionsCorrect: 46,
    questionsWrong: 7,
    questionsUnattempted: 2,
    accuracyPercentage: 84,
    difficulty: 'Hard',
    isBookmarked: false,
    priority: 'High',
    isWeakTopic: false
  },
  {
    id: 'zoo-22',
    subject: 'Zoology',
    title: 'Strategies for Enhancement in Food Production',
    unitName: 'Food Production',
    classLevel: 'Class 12',
    weightagePercentage: 3,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-08-26',
    revisionCount: 2,
    studyTimeMinutes: 80,
    questionsSolved: 25,
    questionsCorrect: 24,
    questionsWrong: 1,
    questionsUnattempted: 0,
    accuracyPercentage: 96,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  },
  {
    id: 'zoo-23',
    subject: 'Zoology',
    title: 'Microbes in Human Welfare',
    unitName: 'Microbes',
    classLevel: 'Class 12',
    weightagePercentage: 4,
    status: 'Completed',
    completionPercentage: 100,
    lastRevisionDate: '2026-09-02',
    revisionCount: 2,
    studyTimeMinutes: 100,
    questionsSolved: 35,
    questionsCorrect: 33,
    questionsWrong: 2,
    questionsUnattempted: 0,
    accuracyPercentage: 94,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  },
  {
    id: 'zoo-24',
    subject: 'Zoology',
    title: 'Organisms and Populations',
    unitName: 'Ecology',
    classLevel: 'Class 12',
    weightagePercentage: 5,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2027-01-05',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'zoo-25',
    subject: 'Zoology',
    title: 'Ecosystem',
    unitName: 'Ecology',
    classLevel: 'Class 12',
    weightagePercentage: 4,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2027-01-15',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  },
  {
    id: 'zoo-26',
    subject: 'Zoology',
    title: 'Biodiversity and Conservation',
    unitName: 'Ecology',
    classLevel: 'Class 12',
    weightagePercentage: 5,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2027-01-25',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Medium',
    isWeakTopic: false
  },
  {
    id: 'zoo-27',
    subject: 'Zoology',
    title: 'Environmental Issues',
    unitName: 'Ecology',
    classLevel: 'Class 12',
    weightagePercentage: 4,
    status: 'Not Started',
    completionPercentage: 0,
    targetCompletionDate: '2027-02-05',
    revisionCount: 0,
    studyTimeMinutes: 0,
    questionsSolved: 0,
    questionsCorrect: 0,
    questionsWrong: 0,
    questionsUnattempted: 0,
    accuracyPercentage: 0,
    difficulty: 'Easy',
    isBookmarked: false,
    priority: 'Low',
    isWeakTopic: false
  }
];
