# Project-wide Gradle settings.
# Specifies the JVM arguments used for the daemon process.
# Tweaking heap memory to avoid OutOfMemoryError during dex merging and code generation.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseG1GC

# Enable parallel execution and build caching
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX support
android.useAndroidX=true

# Kotlin Daemon JVM arguments
kotlin.daemon.jvmargs=-Xmx2048m

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
